package com.rgapro1.ocaso;

import android.Manifest;import android.app.AlertDialog;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.MediaStore;import android.view.Gravity;import android.view.View;import android.widget.*;import androidx.biometric.BiometricManager;import androidx.biometric.BiometricPrompt;import androidx.core.content.ContextCompat;import androidx.core.content.FileProvider;import androidx.fragment.app.FragmentActivity;import org.json.*;import java.io.*;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.Executor;import java.util.concurrent.Executors;

/** Production UI focused on the approved OCR fields and RGA PRO identity. */
public class MainActivityCore extends FragmentActivity{
 private static final int NAVY=0xff0c2343,BLUE=0xff1985e0,BG=0xfff7f9fc,TEXT=0xff1c2736,MUTED=0xff687588,LINE=0xffe1e6ed,CAMERA=7101,IMAGE=7102,PDF=7103;
 private SharedPreferences prefs;private String user;private LinearLayout content;private File scanFile;private Uri scanUri;private boolean dniMode;private int dniSide;private final ArrayList<String> paths=new ArrayList<>();private final ArrayList<String> texts=new ArrayList<>();private final Executor bio=Executors.newSingleThreadExecutor();
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private TextView tv(String s,float z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setTypeface(null,b?1:0);v.setPadding(dp(6),dp(6),dp(6),dp(6));return v;}private EditText edit(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setTextSize(16);e.setPadding(dp(14),0,dp(14),0);return e;}private android.graphics.drawable.GradientDrawable bg(int c,int r){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),LINE);return g;}private Button btn(String s,boolean p){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(p?Color.WHITE:TEXT);b.setBackground(bg(p?BLUE:Color.WHITE,18));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);prefs=getSharedPreferences("rgapro_local",MODE_PRIVATE);if(prefs.contains("user"))loginPage();else createPage();}
 private void logo(LinearLayout l){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER);RgaBrandView v=new RgaBrandView(this);h.addView(v,new LinearLayout.LayoutParams(dp(150),dp(150)));l.addView(h);l.addView(tv("RgaPro",30,NAVY,true));}
 private void createPage(){LinearLayout l=col();l.setGravity(Gravity.CENTER_HORIZONTAL);l.setBackgroundColor(BG);l.setPadding(dp(24),dp(20),dp(24),dp(24));logo(l);l.addView(tv("Gestión de pólizas y clientes",20,TEXT,true));EditText u=edit("Usuario"),p=edit("Clave de 6 dígitos"),p2=edit("Repite la clave");p.setInputType(18);p2.setInputType(18);l.addView(u);l.addView(p);l.addView(p2);Button b=btn("Crear acceso",true);l.addView(b);b.setOnClickListener(v->{if(u.getText().toString().trim().isEmpty()||!p.getText().toString().matches("\\d{6}")||!p.getText().toString().equals(p2.getText().toString())){toast("Usa una clave de 6 dígitos y repítela");return;}prefs.edit().putString("user",u.getText().toString().trim()).putString("pin",p.getText().toString()).putBoolean("biometric",true).apply();user=u.getText().toString().trim();home();});setContentView(l);}
 private void loginPage(){LinearLayout l=col();l.setGravity(Gravity.CENTER_HORIZONTAL);l.setBackgroundColor(BG);l.setPadding(dp(24),dp(20),dp(24),dp(24));logo(l);Button k=btn("🔐 Entrar con clave",true),b=btn("● Entrar con huella / biometría",false);l.addView(k);l.addView(b);k.setOnClickListener(v->login());b.setOnClickListener(v->biometricLogin());setContentView(l);}
 private void login(){EditText e=edit("Clave de 6 dígitos");e.setInputType(18);AlertDialog d=new AlertDialog.Builder(this).setTitle("Entrar").setView(e).setNegativeButton("Cancelar",null).setPositiveButton("Entrar",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(prefs.getString("pin","").equals(e.getText().toString())){d.dismiss();user=prefs.getString("user","");home();}else e.setError("Clave incorrecta");}));d.show();}
 private void biometricLogin(){if(!prefs.getBoolean("biometric",true)||BiometricManager.from(this).canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_WEAK)!=BiometricManager.BIOMETRIC_SUCCESS){toast("Biometría no disponible. Usa la clave.");return;}new BiometricPrompt(this,bio,new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){runOnUiThread(()->{user=prefs.getString("user","");home();});}}).authenticate(new BiometricPrompt.PromptInfo.Builder().setTitle("RgaPro").setSubtitle("Acceso seguro").setNegativeButtonText("Usar clave").setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_WEAK).build());}
 private void home(){LinearLayout root=col();root.setBackgroundColor(BG);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setBackgroundColor(NAVY);RgaBrandView logo=new RgaBrandView(this);h.addView(logo,new LinearLayout.LayoutParams(dp(54),dp(54)));h.addView(tv("RgaPro\nGestión profesional",18,Color.WHITE,true));root.addView(h);LinearLayout b=col();b.setPadding(dp(14),dp(14),dp(14),dp(20));menu(b,"👤","Clientes","Datos personales y pólizas",v->clients());menu(b,"🛡","Pólizas","Producto y número de póliza",v->policies());menu(b,"▤","Escanear / OCR","DNI, NIE, JPEG y PDF",v->scan());menu(b,"🔔","Vencimientos","Próximas bajas",v->expiries());menu(b,"🔒","Seguridad","Biometría",v->security());ScrollView s=new ScrollView(this);s.addView(b);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void menu(LinearLayout b,String i,String t,String sub,View.OnClickListener c){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(12),dp(8),dp(12),dp(8));x.setBackground(bg(Color.WHITE,18));x.addView(tv(i,27,BLUE,true));LinearLayout w=col();w.addView(tv(t,18,TEXT,true));w.addView(tv(sub,13,MUTED,false));x.addView(w,new LinearLayout.LayoutParams(0,dp(68),1));x.addView(tv("›",30,MUTED,false));x.setOnClickListener(c);b.addView(x,new LinearLayout.LayoutParams(-1,dp(86)));}
 private void page(String title,String sub){LinearLayout r=col();r.setBackgroundColor(BG);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setBackgroundColor(NAVY);Button back=btn("‹",false);back.setTextColor(Color.WHITE);back.setBackgroundColor(Color.TRANSPARENT);back.setOnClickListener(v->home());h.addView(back,new LinearLayout.LayoutParams(dp(48),dp(54)));h.addView(tv(title+"\n"+sub,19,Color.WHITE,true));r.addView(h);content=col();content.setPadding(dp(14),dp(14),dp(14),dp(20));ScrollView s=new ScrollView(this);s.addView(content);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);}
 private JSONArray data(){try{return new JSONArray(prefs.getString("policies","[]"));}catch(Exception e){return new JSONArray();}}private void save(JSONArray a){prefs.edit().putString("policies",a.toString()).apply();}
 private void clients(){page("Clientes","Nombre, DNI, teléfono, email o póliza");EditText q=edit("Buscar…");content.addView(q);LinearLayout list=col();content.addView(list);Runnable r=()->{list.removeAllViews();String n=q.getText().toString().toLowerCase(Locale.ROOT);JSONArray a=data();for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;String h=(p.optString("holder")+" "+p.optString("identityNumber")+" "+p.optString("phone")+" "+p.optString("email")+" "+p.optString("number")).toLowerCase(Locale.ROOT);if(n.isEmpty()||h.contains(n)){Button x=btn("👤 "+p.optString("holder","Sin titular")+"\n"+p.optString("identityNumber","")+" · "+p.optString("type","Cliente")+" · "+p.optString("number",""),false);x.setOnClickListener(v->detail(p));list.addView(x);}}};q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){r.run();}public void afterTextChanged(android.text.Editable e){}});r.run();}
 private void detail(JSONObject p){new AlertDialog.Builder(this).setTitle("Ficha de cliente").setMessage("Nombre y apellidos: "+p.optString("holder","—")+"\nDNI/NIE: "+p.optString("identityNumber",p.optString("holderDni","—"))+"\nFecha de nacimiento: "+p.optString("birthDate","—")+"\nTeléfono: "+p.optString("phone","—")+"\nDirección: "+p.optString("address","—")+"\nEmail: "+p.optString("email","—")+"\n\nProducto: "+p.optString("type","—")+"\nNº de póliza: "+p.optString("number","—")).setPositiveButton("Cerrar",null).show();}
 private void policies(){page("Pólizas","Producto y número son prioritarios");Spinner sp=new Spinner(this);String[] t={"Todas","Auto","Hogar","Vida","Salud","Decesos Integral","Asistencia Familiar XXI","Empresa","Otros"};sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,t));content.addView(sp);LinearLayout list=col();content.addView(list);Runnable r=()->{list.removeAllViews();String f=String.valueOf(sp.getSelectedItem());JSONArray a=data();for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p!=null&&(f.equals("Todas")||f.equalsIgnoreCase(p.optString("type","Otros")))){Button x=btn("🛡 "+p.optString("type","Otros")+"\nNº póliza: "+p.optString("number","—")+"\nTitular: "+p.optString("holder","—"),false);x.setOnClickListener(v->detail(p));list.addView(x);}}};sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> a,View v,int p,long id){r.run();}public void onNothingSelected(android.widget.AdapterView<?> a){}});r.run();}
 private void expiries(){page("Vencimientos","Próximas 60 días");JSONArray a=data();SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy",Locale.ROOT);Date now=new Date();boolean any=false;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);try{String ex=p.optString("expiry",p.optString("validityDate"));if(ex.isEmpty())continue;long d=(f.parse(ex).getTime()-now.getTime())/86400000L;if(d>=0&&d<=60){any=true;content.addView(tv("⚠ "+p.optString("holder","Sin titular")+" · "+p.optString("type","Otros")+"\nNº póliza: "+p.optString("number","—")+" · "+d+" días · "+ex,16,TEXT,true));}}catch(Exception ignored){}}if(!any)content.addView(tv("No hay pólizas en los próximos 60 días.",16,MUTED,false));}
 private void security(){page("Seguridad","Acceso local");Switch b=new Switch(this);b.setText("Permitir acceso biométrico");b.setChecked(prefs.getBoolean("biometric",true));content.addView(b);b.setOnCheckedChangeListener((x,v)->prefs.edit().putBoolean("biometric",v).apply());content.addView(tv("Las fotos y datos se guardan localmente.",14,MUTED,false));}
 private void scan(){page("Escanear / OCR","DNI/NIE · JPEG · PDF");content.addView(tv("DNI/NIE: nombre, apellidos, DNI/NIE y fecha de nacimiento. Pólizas: tipo de producto y número de póliza. Teléfono, dirección y email son opcionales.",15,MUTED,false));Button d=btn("🪪 DNI / NIE · anverso + reverso",true),j=btn("🖼 JPEG/JPG",false),p=btn("📄 PDF",false);content.addView(d);content.addView(j);content.addView(p);d.setOnClickListener(v->{reset();dniMode=true;openCamera();});j.setOnClickListener(v->{reset();dniMode=false;pickImages();});p.setOnClickListener(v->{reset();dniMode=false;pickPdf();});}
 private void reset(){paths.clear();texts.clear();dniSide=0;}private void openCamera(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA);return;}try{File d=new File(getCacheDir(),"scans");if(!d.exists())d.mkdirs();scanFile=File.createTempFile("rga_",".jpg",d);scanUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",scanFile);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,scanUri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(i,CAMERA);}catch(Exception e){toast("No se pudo abrir la cámara");}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==CAMERA&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)openCamera();}private void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMAGE);}private void pickPdf(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/pdf");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PDF);}
 @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(result!=RESULT_OK)return;try{if(r==CAMERA){paths.add(copyFile(scanFile));if(dniMode&&dniSide==0){dniSide=1;processLast(true);}else processLast(false);}else if(r==IMAGE&&data!=null){if(data.getClipData()!=null){ClipData c=data.getClipData();for(int i=0;i<c.getItemCount();i++){String p=copyUri(c.getItemAt(i).getUri(),"jpg");if(p!=null)paths.add(p);}}else if(data.getData()!=null){String p=copyUri(data.getData(),"jpg");if(p!=null)paths.add(p);}processAll(0);}else if(r==PDF&&data!=null){Uri u=data.getData();String p=copyUri(u,"pdf");if(p!=null)paths.add(p);PdfOcrHelper.process(this,u,new PdfOcrHelper.Callback(){public void onSuccess(String t){runOnUiThread(()->{texts.add(t);showOcr(t);});}public void onError(Exception e){runOnUiThread(()->toast("No se pudo leer el PDF"));}});}}catch(Exception e){toast("No se pudo procesar el documento");}}
 private void processLast(boolean askBack){ocr(paths.get(paths.size()-1),new Cb(){public void ok(String t){texts.add(t);if(askBack)new AlertDialog.Builder(MainActivityCore.this).setTitle("Anverso leído").setMessage("Ahora fotografía el REVERSO del DNI/NIE.").setNegativeButton("Cancelar",null).setPositiveButton("Fotografiar reverso",(d,w)->openCamera()).show();else showOcr(join());}public void err(){toast("No se pudo leer la imagen");}});}
 private void processAll(int i){if(i>=paths.size()){showOcr(join());return;}ocr(paths.get(i),new Cb(){public void ok(String t){texts.add(t);processAll(i+1);}public void err(){processAll(i+1);}});}private interface Cb{void ok(String t);void err();}
 private void ocr(String path,Cb cb){new Thread(()->{try{android.graphics.Bitmap bm=android.graphics.BitmapFactory.decodeFile(path);if(bm==null)throw new IOException();com.google.mlkit.vision.common.InputImage im=com.google.mlkit.vision.common.InputImage.fromBitmap(bm,0);com.google.mlkit.vision.text.TextRecognizer rec=com.google.mlkit.vision.text.TextRecognition.getClient(com.google.mlkit.vision.text.latin.TextRecognizerOptions.DEFAULT_OPTIONS);rec.process(im).addOnSuccessListener(x->{String t=x.getText();bm.recycle();rec.close();runOnUiThread(()->cb.ok(t));}).addOnFailureListener(x->{bm.recycle();rec.close();runOnUiThread(cb::err);});}catch(Exception e){runOnUiThread(cb::err);}}).start();}
 private String join(){StringBuilder b=new StringBuilder();for(String s:texts)b.append(s).append('\n');return b.toString();}private String copyFile(File a)throws IOException{File d=new File(getFilesDir(),"documents");if(!d.exists())d.mkdirs();File b=new File(d,"scan_"+System.currentTimeMillis()+".jpg");copy(a,b);return b.getAbsolutePath();}private String copyUri(Uri u,String ext){try{File d=new File(getFilesDir(),"documents");if(!d.exists())d.mkdirs();File b=new File(d,"doc_"+System.currentTimeMillis()+"."+ext);InputStream i=getContentResolver().openInputStream(u);if(i==null)return null;OutputStream o=new FileOutputStream(b);byte[] z=new byte[8192];int n;while((n=i.read(z))>0)o.write(z,0,n);i.close();o.close();return b.getAbsolutePath();}catch(Exception e){return null;}}private void copy(File a,File b)throws IOException{InputStream i=new FileInputStream(a);OutputStream o=new FileOutputStream(b);byte[] z=new byte[8192];int n;while((n=i.read(z))>0)o.write(z,0,n);i.close();o.close();}
 private void showOcr(String raw){OcrReviewDialog.show(this,raw,paths.size(),this::saveOcr);}private void saveOcr(JSONObject in){try{JSONArray a=data();String id=in.optString("identityNumber"),num=in.optString("number");int idx=-1;for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;if(!id.isEmpty()&&id.equalsIgnoreCase(p.optString("identityNumber",p.optString("holderDni","")))){idx=i;break;}if(!num.isEmpty()&&num.equalsIgnoreCase(p.optString("number"))){idx=i;break;}}JSONObject p=idx>=0?a.optJSONObject(idx):new JSONObject();String[] k={"holder","name","surname","identityType","identityNumber","holderDni","birthDate","phone","address","email","type","number","ocrText","insureds","insuredCount"};for(String x:k)if(in.has(x))p.put(x,in.get(x));p.put("updatedAt",System.currentTimeMillis());JSONArray docs=p.optJSONArray("documentPhotos");if(docs==null)docs=new JSONArray();for(int i=0;i<paths.size();i++){JSONObject d=new JSONObject();d.put("path",paths.get(i));d.put("side",dniMode?(i==0?"ANVERSO":"REVERSO"):"DOCUMENTO "+(i+1));docs.put(d);}p.put("documentPhotos",docs);if(idx>=0)a.put(idx,p);else a.put(p);save(a);toast(num.isEmpty()?"Cliente guardado":"Póliza guardada");reset();home();}catch(Exception e){toast("No se pudo guardar el resultado OCR");}}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
