from pathlib import Path
P=Path('app/src/main/java/com/rgapro1/ocaso/MainActivityV2.java')
s=P.read_text(encoding='utf-8')
anchor='''        addPolicyField("TELÉFONO",null,policyPhoneE);\n\n        Button accept=btn("✅ ACEPTAR DATOS Y ARCHIVAR PÓLIZA",true),reject=btn("❌ RECHAZAR / VOLVER",false);'''
insert='''        addPolicyField("TELÉFONO",null,policyPhoneE);\n        if("Hogar".equalsIgnoreCase(p.optString("policyType", ""))){\n            addPolicyField("DIRECCIÓN DEL RIESGO",p.optString("riskAddress",""),null);\n            addPolicyField("REFERENCIA CATASTRAL",p.optString("cadastralReference",""),null);\n            addPolicyField("CONTINENTE",p.optString("continent",""),null);\n            addPolicyField("CONTENIDO",p.optString("content",""),null);\n            addPolicyField("VALOR TOTAL ASEGURADO",p.optString("totalInsuredValue",""),null);\n            addPolicyField("FECHA DE EFECTO",p.optString("effectiveDate",""),null);\n            addPolicyField("FECHA DE VENCIMIENTO",p.optString("expiryDate",""),null);\n        }\n\n        Button accept=btn("✅ ACEPTAR DATOS Y ARCHIVAR PÓLIZA",true),reject=btn("❌ RECHAZAR / VOLVER",false);'''
if anchor not in s: raise SystemExit('review anchor not found')
s=s.replace(anchor,insert,1)
# Persist parsed home fields in the policy object.
anchor2='''            pol.put("identityNumber",id);pol.put("address",policyAddressE.getText().toString().trim());pol.put("phone",policyPhoneE.getText().toString().trim());pol.put("email",policyEmailE.getText().toString().trim());pol.put("receipt",receiptE.getText().toString().trim());pol.put("capital",capitalE.getText().toString().trim());'''
insert2='''            pol.put("identityNumber",id);pol.put("address",policyAddressE.getText().toString().trim());pol.put("phone",policyPhoneE.getText().toString().trim());pol.put("email",policyEmailE.getText().toString().trim());pol.put("receipt",receiptE.getText().toString().trim());pol.put("capital",capitalE.getText().toString().trim());pol.put("birthDate",parsed.optString("birthDate",""));pol.put("riskAddress",parsed.optString("riskAddress",""));pol.put("cadastralReference",parsed.optString("cadastralReference",""));pol.put("continent",parsed.optString("continent",""));pol.put("content",parsed.optString("content",""));pol.put("totalInsuredValue",parsed.optString("totalInsuredValue",""));pol.put("effectiveDate",parsed.optString("effectiveDate",""));pol.put("expiryDate",parsed.optString("expiryDate",""));'''
if anchor2 not in s: raise SystemExit('save anchor not found')
s=s.replace(anchor2,insert2,1)
P.write_text(s,encoding='utf-8');print('home fields UI patch applied')